### ISSUE TITLE
Get seqNr

### ISSUE THREAD

**Issue by dispalt** [notxcain/aecor#25]
Is there a plan to expose the seqNr? It's useful to me as an ordered partition increasing number.

**Comment by notxcain** [comment]
@dispalt  What `seqNr` do you refer to and where should it be exposed?

**Comment by dispalt** [comment]
I am referring to the actor's offset (better word for it then sequence number). In straight akka land I'd typically use to use it as a starting point for a journal. e.g.  Give me the current state, (including the sequence number/offset) and then start watching for events from that place on.

**Comment by notxcain** [comment]
Ah, you mean you want to start recovery from specific state and sequence number, rather than from zero?

**Comment by dispalt** [comment]
Well I guess yeah I sometimes use the raw event stream to do stuff, like show an activity log...  And so if I want to look at something from now til whenever I leave, I'd subscribe to the journal stream, starting at the current offset.
